src/pyhn/news/urls.py
#!/usr/bin/env python


from django.conf.urls import patterns, url


urlpatterns = patterns(
    'pyhn.news.views.index',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<cur_page_num>\d+)/$', 'index', name='list'),
    url(r'^newest/$', 'index', {'order_by': '-created_at'}, 'newest'),
    url(r'^newest/(?P<cur_page_num>\d+)/$', 'index', {
        'order_by': '-created_at'
    }, 'newest_list'),
)
urlpatterns += patterns(
    'pyhn.news.views.post',
    url(r'^submit/$', 'submit', name='submit'),
    url(r'^remove/(?P<post_id>\d+)/$', 'remove', name='post_remove'),
)
urlpatterns += patterns(
    'pyhn.news.views.vote',
    url(r'^post/(?P<post_id>\d+)/vote/$', 'post_vote', name='post_vote'),
    url(
        r'^comment/(?P<comment_id>\d+)/vote/$', 'comment_vote',
        name='comment_vote'
    ),
)
urlpatterns += patterns(
    'pyhn.news.views.comment',
    url(r'^post/(?P<post_id>\d+)/comment/$', 'comment_post', name='comment'),
    url(
        r'^comment/(?P<comment_id>\d+)/reply/$', 'reply_comment', name='reply'
    ),
    url(
        r'^comment/(?P<comment_id>\d+)/remove/$', 'remove',
        name='comment_remove'
    ),
)

src/pyhn/urls.py
#!/usr/bin/env python


from django.conf.urls import patterns, include, url

from pyhn.libs.rss import NewsFeed


urlpatterns = patterns(
    '',
    url(r'^$', 'pyhn.apps.news.views.index.index', name='index'),
    url(
        r'^social/', include('social.apps.django_app.urls', namespace='social')
    ),
    url(r'^news/', include('pyhn.apps.news.urls', namespace='news')),
    url(r'^accounts/', include('pyhn.apps.account.urls', namespace='account')),
    url(
        r'^user/(?P<user_id>\d+)/', 'pyhn.apps.account.views.user_profile',
        name='profile'
    ),
)

urlpatterns += patterns(
    '',
    url(r'^rss/$', NewsFeed(), name='rss'),
)

src/pyhn/libs/templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load bootstrap_themes %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <title>{% if PYHN_TITLE %}{{ PYHN_TITLE }}{% else %}Python Hacker News{% endif %}</title>

    {% bootstrap_styles theme=PYHN_THEME type='min.css' %}
    <link rel="stylesheet" href="{% static 'libs/font-awesome-4.3.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libs/sco.js/css/sco.message.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  </head>

  <body>

    {% include 'header.html' %}
    <div class="container">
      {% block container %}{% endblock %}
    </div>
    {% include 'footer.html' %}

    <script src="{% static 'libs/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'libs/jquery.cookie.js' %}"></script>
    {% bootstrap_script use_min=True %}
    <script src="{% static 'libs/sco.js/js/sco.confirm.bs3.js' %}"></script>
    <script src="{% static 'libs/sco.js/js/sco.modal.js' %}"></script>
    <script src="{% static 'libs/sco.js/js/sco.message.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% if PYHN_GOOGLE_ANALYTICS_UA %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '{{ PYHN_GOOGLE_ANALYTICS_UA }}', 'auto');
      ga('send', 'pageview');
    </script>
    {% endif %}
  </body>
</html>

src/pyhn/libs/templates/footer.html
<div id="footer">
  <div class="container">
    <p class="text-muted">
      {% if PYHN_COPYRIGHT %}
      {{ PYHN_COPYRIGHT|safe }}
      {% else %}
      &copy; 2014 <a href="https://github.com/akun">akun</a>. Powered by <a href="https://github.com/akun/PyHackerNews">Python Hacker News</a>. Report <a href="https://github.com/akun/PyHackerNews/issues/new">issue</a>
      {% endif %}
    </p>
  </div>
</div>

src/pyhn/libs/templates/header.html
{% load i18n %}
{% load pyhn_extras %}

<div class="navbar navbar-default navbar-fix-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">{% if PYHN_TITLE %}{{ PYHN_TITLE }}{% else %}Python Hacker News{% endif %}</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'news:newest' %}">{% trans 'New' %}</a></li>
        <li><a href="{% url 'news:submit' %}">{% trans 'Submit' %}</a></li>
        <li><a href="{% url 'rss' %}"><i class="fa fa-rss"></i>&nbsp;{% trans 'RSS' %}</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ request.user.email|gravatar_url }}" /> {{ request.user.username }} <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'account:index' %}">Account</a></li>
            <li><a href="{% url 'account:logout' %}">Sign Out</a></li>
          </ul>
        </li>
        {% else %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ request.user.email|gravatar_url }}" /> {{ request.user.username }} <b class="caret"></b></a>
          <ul class="dropdown-menu">
            {% include 'social_auth_list.html' %}
          </ul>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>

src/pyhn/libs/templates/social_auth_list.html
{% load i18n %}

<li><a href="{% url 'social:begin' 'github' %}">{% trans 'Sign in with GitHub' %}</a></li>
<li><a href="{% url 'social:begin' 'weibo' %}">{% trans 'Sign in with Sina Weibo' %}</a></li>