src/pyhn/apps/news/urls.py
#!/usr/bin/env python


from django.conf.urls import patterns, url


urlpatterns = patterns(
    'pyhn.apps.news.views.index',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<cur_page_num>\d+)/$', 'index', name='list'),
    url(r'^newest/$', 'index', {'order_by': '-created_at'}, 'newest'),
    url(r'^newest/(?P<cur_page_num>\d+)/$', 'index', {
        'order_by': '-created_at'
    }, 'newest_list'),
)
urlpatterns += patterns(
    'pyhn.apps.news.views.post',
    url(r'^submit/$', 'submit', name='submit'),
    url(r'^remove/(?P<post_id>\d+)/$', 'remove', name='post_remove'),
)
urlpatterns += patterns(
    'pyhn.apps.news.views.vote',
    url(r'^post/(?P<post_id>\d+)/vote/$', 'post_vote', name='post_vote'),
    url(
        r'^comment/(?P<comment_id>\d+)/vote/$', 'comment_vote',
        name='comment_vote'
    ),
)
urlpatterns += patterns(
    'pyhn.apps.news.views.comment',
    url(r'^post/(?P<post_id>\d+)/comment/$', 'comment_post', name='comment'),
    url(
        r'^comment/(?P<comment_id>\d+)/reply/$', 'reply_comment', name='reply'
    ),
    url(
        r'^comment/(?P<comment_id>\d+)/remove/$', 'remove',
        name='comment_remove'
    ),
)

src/pyhn/news/urls.py
#!/usr/bin/env python


from django.conf.urls import patterns, url


urlpatterns = patterns(
    'pyhn.news.views.index',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<cur_page_num>\d+)/$', 'index', name='list'),
    url(r'^newest/$', 'index', {'order_by': '-created_at'}, 'newest'),
    url(r'^newest/(?P<cur_page_num>\d+)/$', 'index', {
        'order_by': '-created_at'
    }, 'newest_list'),
)
urlpatterns += patterns(
    'pyhn.news.views.post',
    url(r'^submit/$', 'submit', name='submit'),
    url(r'^remove/(?P<post_id>\d+)/$', 'remove', name='post_remove'),
)
urlpatterns += patterns(
    'pyhn.news.views.vote',
    url(r'^post/(?P<post_id>\d+)/vote/$', 'post_vote', name='post_vote'),
    url(
        r'^comment/(?P<comment_id>\d+)/vote/$', 'comment_vote',
        name='comment_vote'
    ),
)
urlpatterns += patterns(
    'pyhn.news.views.comment',
    url(r'^post/(?P<post_id>\d+)/comment/$', 'comment_post', name='comment'),
    url(
        r'^comment/(?P<comment_id>\d+)/reply/$', 'reply_comment', name='reply'
    ),
    url(
        r'^comment/(?P<comment_id>\d+)/remove/$', 'remove',
        name='comment_remove'
    ),
)

src/pyhn/urls.py
#!/usr/bin/env python


from django.conf.urls import patterns, include, url

from pyhn.libs.rss import NewsFeed


urlpatterns = patterns(
    '',
    url(r'^$', 'pyhn.apps.news.views.index.index', name='index'),
    url(
        r'^social/', include('social.apps.django_app.urls', namespace='social')
    ),
    url(r'^news/', include('pyhn.apps.news.urls', namespace='news')),
    url(r'^accounts/', include('pyhn.apps.account.urls', namespace='account')),
    url(
        r'^user/(?P<user_id>\d+)/', 'pyhn.apps.account.views.user_profile',
        name='profile'
    ),
)

urlpatterns += patterns(
    '',
    url(r'^rss/$', NewsFeed(), name='rss'),
)

src/pyhn/apps/news/models.py
#!/usr/bin/env python


from django.db import models
from django.utils import timezone


class Post(models.Model):
    user = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    url = models.URLField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    score = models.FloatField(default=0.0)

    class Meta:
        ordering = ['-score', '-created_at']
        permissions = (
            ('can_submit', 'Can submit new post'),
        )

    def __unicode__(self):
        return self.title

    def vote(self, user):
        """
        ref: http://www.ruanyifeng.com/blog/2012/02/ranking_algorithm_hacker_news.html
        """

        Vote.objects.create(user=user, post=self)

        score = get_score(self.vote_set.count(), self.created_at)
        self.score = score
        self.save()

        return score


class Vote(models.Model):
    user = models.ForeignKey('auth.User')
    post = models.ForeignKey('Post')

    def __unicode__(self):
        return '%s, %s' % (self.user.username, self.post.title)


class Comment(models.Model):
    user = models.ForeignKey('auth.User')
    parent = models.ForeignKey('self', null=True, blank=True)
    post = models.ForeignKey('Post')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    score = models.FloatField(default=0.0)

    class Meta:
        ordering = ['-score', '-created_at']

    def __unicode__(self):
        return '%s, %s' % (self.user, self.post)

    def vote(self, user):
        CommentVote.objects.create(user=user, comment=self)

        score = get_score(self.commentvote_set.count(), self.created_at)
        self.score = score
        self.save()

        return score


class CommentVote(models.Model):
    user = models.ForeignKey('auth.User')
    comment = models.ForeignKey('Comment')

    def __unicode__(self):
        return '%s, %s' % (self.user.username, self.comment.content[:10])


def get_score(param_count, created_at):
    param_count = param_count - 1 if param_count > 0 else 0
    timedelta = (timezone.now() - created_at)
    param_time = timedelta.days * 24 + timedelta.seconds / 3600
    param_base = 1.8
    score = param_count / (param_time + 2)**param_base
    return score

src/pyhn/apps/news/views/comment.py
#!/usr/bin/env python


import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import redirect_to_login
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST, require_http_methods

from pyhn.apps.news.forms import CommentForm, ReplyForm
from pyhn.apps.news.models import Comment, Post
from pyhn.apps.news.views.common import format_post


@require_http_methods(['GET', 'POST'])
def comment_post(request, post_id):

    post = get_object_or_404(Post, id=post_id)
    reply_form = ReplyForm()

    if request.method == 'GET':
        format_post(request, post)
        comment_form = CommentForm()
    else:
        if not request.user.is_authenticated():
            path = request.get_full_path()
            return redirect_to_login(path)

        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form.save(request.user, post)
            return HttpResponseRedirect(reverse('news:comment', kwargs={
                'post_id': post_id
            }))

    comments = Comment.objects.filter(post=post, parent=None)

    return render(request, 'news/comment.html', {
        'comment_form': comment_form,
        'reply_form': reply_form,
        'post': post,
        'show_index': False,
        'comments': comments,
    })


@require_POST
def reply_comment(request, comment_id):

    comment = get_object_or_404(Comment, id=comment_id)
    ret = {'code': 0, 'msg': 'success', 'result': {'id': comment.id}}
    if request.user.is_authenticated():
        form = ReplyForm(request.POST)
        if form.is_valid():
            form.save(request.user, comment)
        else:
            ret['code'] = 101
            ret['msg'] = 'form is invalid'
            ret['result']['errors'] = dict(form.errors)
    else:
        ret['code'] = 100
        ret['msg'] = 'need login'

    return HttpResponse(json.dumps(ret, ensure_ascii=False), content_type='application/json')


@login_required
@require_POST
def remove(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    ret = {'code': 0, 'msg': 'success', 'result': {'id': comment_id}}
    return HttpResponse(json.dumps(ret, ensure_ascii=False), content_type='application/json')

src/pyhn/apps/news/views/common.py
#!/usr/bin/env python


from urlparse import urlparse

from django.core.paginator import EmptyPage, InvalidPage, Paginator


def format_post(request, post):
    post.voted = False
    is_authenticated = request.user.is_authenticated()
    if is_authenticated and post.vote_set.filter(user=request.user).count():
        post.voted = True
    if post.url:
        post.netloc = urlparse(post.url).netloc


def get_paged_object(source_items, cur_page_num, num_per_page):
    paginator = Paginator(source_items, num_per_page)
    try:
        page = int(cur_page_num)
    except ValueError:
        page = 1

    try:
        paged_object = paginator.page(page)
    except (EmptyPage, InvalidPage):
        paged_object = paginator.page(paginator.num_pages)

    return paged_object

src/pyhn/apps/news/views/index.py
#!/usr/bin/env python


from django.shortcuts import render
from django.views.decorators.http import require_GET

from pyhn.apps.news.models import Post
from pyhn.apps.news.views.common import format_post, get_paged_object


@require_GET
def index(request, cur_page_num=1, order_by=None):
    cur_page_num = int(cur_page_num)
    num_per_page = 30

    posts = Post.objects.all()
    if order_by:
        posts = posts.order_by(order_by)
    paged_object = get_paged_object(posts, cur_page_num, num_per_page)
    for post in paged_object.object_list:
        format_post(request, post)

    return render(request, 'news/list.html', {
        'paged_object': paged_object,
        'start_index': num_per_page * (cur_page_num - 1),
        'show_index': True,
    })

src/pyhn/apps/news/views/post.py
#!/usr/bin/env python


import json

from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST, require_http_methods

from pyhn.apps.news.forms import PostForm
from pyhn.apps.news.models import Post


@login_required
@permission_required('news.can_submit')
@require_http_methods(['GET', 'POST'])
def submit(request):

    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save(request.user)
            return HttpResponseRedirect(reverse('index'))

    return render(request, 'news/submit.html', {'form': form})


@login_required
@require_POST
def remove(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    ret = {'code': 0, 'msg': 'success', 'result': {'id': post_id}}
    return HttpResponse(json.dumps(ret, ensure_ascii=False), content_type='application/json')

src/pyhn/apps/news/views/vote.py
#!/usr/bin/env python


import json

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

from pyhn.apps.news.models import Comment, Post


@require_POST
def post_vote(request, post_id):
    return do_vote(request, post_id, Post)


@require_POST
def comment_vote(request, comment_id):
    return do_vote(request, comment_id, Comment)


def do_vote(request, object_id, object_class):
    set_dict = {
        Post: 'vote_set',
        Comment: 'commentvote_set',
    }
    if not request.user.is_authenticated():
        ret = {'code': 100, 'msg': 'need login', 'result': {'id': object_id}}
    else:
        object_instance = get_object_or_404(object_class, id=object_id)
        votes = getattr(object_instance, set_dict[object_class])
        if votes.filter(user=request.user).count():
            ret = {
                'code': 101, 'msg': 'has voted', 'result': {'id': object_id}
            }
        else:
            object_instance.vote(request.user)
            ret = {'code': 0, 'msg': 'success', 'result': {'id': object_id}}
    return HttpResponse(
        json.dumps(ret, ensure_ascii=False), content_type='application/json'
    )

src/pyhn/news/views/comment.py
#!/usr/bin/env python


import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import redirect_to_login
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST, require_http_methods

from pyhn.news.forms import CommentForm, ReplyForm
from pyhn.news.models import Comment, Post
from pyhn.news.views.common import format_post


@require_http_methods(['GET', 'POST'])
def comment_post(request, post_id):

    post = get_object_or_404(Post, id=post_id)
    reply_form = ReplyForm()

    if request.method == 'GET':
        format_post(request, post)
        comment_form = CommentForm()
    else:
        if not request.user.is_authenticated():
            path = request.get_full_path()
            return redirect_to_login(path)

        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form.save(request.user, post)
            return HttpResponseRedirect(reverse('news:comment', kwargs={
                'post_id': post_id
            }))

    comments = Comment.objects.filter(post=post, parent=None)

    return render(request, 'news/comment.html', {
        'comment_form': comment_form,
        'reply_form': reply_form,
        'post': post,
        'show_index': False,
        'comments': comments,
    })


@require_POST
def reply_comment(request, comment_id):

    comment = get_object_or_404(Comment, id=comment_id)
    ret = {'code': 0, 'msg': 'success', 'result': {'id': comment.id}}
    if request.user.is_authenticated():
        form = ReplyForm(request.POST)
        if form.is_valid():
            form.save(request.user, comment)
        else:
            ret['code'] = 101
            ret['msg'] = 'form is invalid'
            ret['result']['errors'] = dict(form.errors)
    else:
        ret['code'] = 100
        ret['msg'] = 'need login'

    return HttpResponse(json.dumps(ret, ensure_ascii=False), content_type='application/json')


@login_required
@require_POST
def remove(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    ret = {'code': 0, 'msg': 'success', 'result': {'id': comment_id}}
    return HttpResponse(json.dumps(ret, ensure_ascii=False), content_type='application/json')

src/pyhn/news/views/index.py
#!/usr/bin/env python


from django.shortcuts import render
from django.views.decorators.http import require_GET

from pyhn.news.models import Post
from pyhn.news.views.common import format_post, get_paged_object


@require_GET
def index(request, cur_page_num=1, order_by=None):
    cur_page_num = int(cur_page_num)
    num_per_page = 30

    posts = Post.objects.all()
    if order_by:
        posts = posts.order_by(order_by)
    paged_object = get_paged_object(posts, cur_page_num, num_per_page)
    for post in paged_object.object_list:
        format_post(request, post)

    return render(request, 'news/list.html', {
        'paged_object': paged_object,
        'start_index': num_per_page * (cur_page_num - 1),
        'show_index': True,
    })

src/pyhn/news/views/post.py
#!/usr/bin/env python


import json

from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST, require_http_methods

from pyhn.news.forms import PostForm
from pyhn.news.models import Post


@login_required
@permission_required('news.can_submit')
@require_http_methods(['GET', 'POST'])
def submit(request):

    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save(request.user)
            return HttpResponseRedirect(reverse('index'))

    return render(request, 'news/submit.html', {'form': form})


@login_required
@require_POST
def remove(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    ret = {'code': 0, 'msg': 'success', 'result': {'id': post_id}}
    return HttpResponse(json.dumps(ret, ensure_ascii=False), content_type='application/json')

src/pyhn/news/views/vote.py
#!/usr/bin/env python


import json

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

from pyhn.news.models import Comment, Post


@require_POST
def post_vote(request, post_id):
    return do_vote(request, post_id, Post)


@require_POST
def comment_vote(request, comment_id):
    return do_vote(request, comment_id, Comment)


def do_vote(request, object_id, object_class):
    set_dict = {
            Post: 'vote_set',
            Comment: 'commentvote_set',
    }
    if not request.user.is_authenticated():
        ret = {'code': 100, 'msg': 'need login', 'result': {'id': object_id}}
    else:
        object_instance = get_object_or_404(object_class, id=object_id)
        if getattr(object_instance, set_dict[object_class]).filter(
            user=request.user
        ).count():
            ret = {
                'code': 101, 'msg': 'has voted', 'result': {'id': object_id}
            }
        else:
            object_instance.vote(request.user)
            ret = {'code': 0, 'msg': 'success', 'result': {'id': object_id}}
    return HttpResponse(
        json.dumps(ret, ensure_ascii=False), content_type='application/json'
    )

src/pyhn/apps/news/templates/news/comment.html
{% extends 'base.html' %}
{% load i18n %}

{% block container %}

{% include "news/item.html" %}

<div class="row comment">
  {% with form=comment_form action='.' %}
  {% include "news/comment_form.html" %}
  {% endwith %}
</div>

<div class="hide">
  {% with form=reply_form id="id_reply_form" %}
  {% include "news/comment_form.html" %}
  {% endwith %}
</div>

<div class="row comments">
  {% include "news/comment_tree.html" %}
</div>

{% endblock %}

src/pyhn/apps/news/templates/news/comment_form.html
{% load i18n %}

<form id="{{ id }}" method="post" action="{{ action }}">{% csrf_token %}
  <div class="row">
    <div class="col-xs-12">
      <div class="form-group{% if form.content.errors %} has-error{% endif %}">
        {{ form.content }}
        <span class="help-block">{{ form.content.errors|striptags }}</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <button type="submit" class="btn btn-default">{% trans '确定' %}</button>
    </div>
  </div>
</form>

src/pyhn/apps/news/templates/news/comment_tree.html
{% load i18n%}
{% load news_extras %}

{% for comment in comments %}
<ul class="tree">
  <li>
    <h6 id="{{ comment.id }}">
      <small>
        <span class="vote">
          {% if not comment|comment_voted:request.user %}
          <a class="up" href="{% url 'news:comment_vote' comment.id %}"><span class="glyphicon glyphicon-thumbs-up btn-sm"></span></a>
          {% endif %}
        </span>
        <span id="id-point-{{ comment.id }}">{{ comment.commentvote_set.count }}</span> point by {{ comment.user.username }} {{ comment.created_at|timesince }} ago | <a href="#{{ comment.id }}">link</a>
        {% if request.user == comment.user %}
        | <a class="remove" href="{% url 'news:comment_remove' comment.id %}"><span class="glyphicon glyphicon-trash"></span> remove</a>
        {% endif %}
      </small>
    </h6>
    <pre>{{ comment.content }}</pre>
    <h6><a class="reply" data-action="{% url 'news:reply' comment.id %}" data-id="{{ comment.id }}" href="#reply">{% trans '回复' %}</a></h6>
    <div id="id_comment_{{ comment.id }}"></div>

    {% if comment.comment_set.count %}
    {% with comments=comment.comment_set.all filename='news/comment_tree.html' %}
    {% include filename %}
    {% endwith %}
    {% endif %}
  </li>
</ul>
{% endfor %}

src/pyhn/apps/news/templates/news/item.html
{% load i18n %}
{% load pyhn_extras %}

<div class="row news">
  <div class="col-md-12">
    <h4 class="title">
      <small>{% if show_index %}{{ start_index|add:forloop.counter }}.{% endif %}</small>
      <span class="vote">
        {% if not post.voted %}
        <a class="up" href="{% url 'news:post_vote' post.id %}"><span class="glyphicon glyphicon-thumbs-up btn-sm"></span></a>
        {% endif %}
      </span>
      {% if post.url %}
      <a href="{{ post.url }}">{{ post.title }}</a>
      {% else %}
      <a href="{% url 'news:comment' post.id %}">{{ post.title }}</a>
      {% endif %}
      <small>{% if post.netloc %}{{ post.netloc }}{% endif %}</small>
    </h4>
    <h6 class="sub">
      <small>
        <span id="id-point-{{ post.id }}">{{ post.vote_set.count }}</span> point |
        {% trans '投递：' %}<a href="{% url 'profile' post.user.id %}"><img src="{{ post.user.email|gravatar_url }}" /> {{ post.user.username }}</a> |
        {% trans '时间：' %}{{ post.created_at|timesince }} ago |
        {% trans '评论：' %}<a href="{% url 'news:comment' post.id %}"><span class="glyphicon glyphicon-comment"></span> {{ post.comment_set.count }}</a>
        {% if request.user == post.user %}
        | <a class="remove" href="{% url 'news:post_remove' post.id %}"><span class="glyphicon glyphicon-trash"></span> remove</a>
        {% endif %}
      </small>
    </h6>
  </div>
</div>

src/pyhn/apps/news/templates/news/list.html
{% extends 'base.html' %}
{% load i18n %}

{% block container %}

{% for post in paged_object.object_list %}
{% include "news/item.html" %}
{% endfor %}

{% if paged_object.has_other_pages %}
<ul class="pagination pagination-sm">
  {% if paged_object.has_previous %}
  <li><a href="{% url 'news:list' paged_object.previous_page_number %}">{% trans '上一页' %}</a>
  {% else %}
  <li class="disabled"><span>{% trans '上一页' %}</span></li>
  {% endif %}
  {% if paged_object.has_next %}
  <li><a href="{% url 'news:list' paged_object.next_page_number %}">{% trans '下一页' %}</a>
  {% else %}
  <li class="disabled"><span>{% trans '下一页' %}</span></li>
  {% endif %}
</ul>
{% endif %}

{% endblock %}

src/pyhn/apps/news/templates/news/submit.html
{% extends 'base.html' %}
{% load i18n %}

{% block container %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{% trans 'New' %}</h3>
  </div>
  <div class="panel-body">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.auto_id }}" class="col-sm-2 control-label">{{ field.label }}</label>
        <div class="col-sm-10{% if field.errors %} has-error{% endif %}">
          {{ field }}
          <span class="help-block">{{ field.errors|striptags }}</span>
        </div>
      </div>
      {% endfor %}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
          <button type="submit" class="btn btn-default">{% trans 'Submit' %}</button>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-8">
          {% trans 'Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the comments page. If there is a url, the text will be ignored.' %}
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}